version: '3'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    environment:
      NODE_ENV: development

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      NODE_ENV: development
