services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/nexusdb

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      NODE_ENV: development

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data: # Named volume for MongoDB persistence